name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: install mosquitto
        run: sudo apt-get update && sudo apt-get install -y mosquitto mosquitto-clients
      - name: Cargo clippy
        run: cargo clippy
      - name: Cargo test
        run: cargo test --verbose
        env:
          RUST_TEST_THREADS: 1
      - name: Cargo build
        run: cargo build --release
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/release/libmosquitto_jwt_auth.so
