name: Coverage
on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: install mosquitto
        run: sudo apt-get update && sudo apt-get install -y mosquitto mosquitto-clients
      - name: install rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - name: install grcov
        run: cargo install grcov
      - name: Coverage
        env:
          RUSTFLAGS: "-C instrument-coverage"
          LLVM_PROFILE_FILE: "mshrtsr-%p-%m.profraw"
          RUST_TEST_THREADS: 1
        run: >
          cargo build &&
          cargo test &&
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
      - uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: lcov.info
